[package]
name = "example"
version = "0.1.0"
authors = ["faineance <faineance@users.noreply.github.com>"]
build = "build.rs"

[lib]
name = "example"
crate-type = ["dylib"] 


[dependencies]
redismodule = { path = "../../redismodule" }
libc= "*"


[build-dependencies]
gcc = "*"