[package]
name = "redismodule"
description = "Write Redis modules in Rust"
version = "0.1.2"
authors = ["faineance <faineance@users.noreply.github.com>"]
license = "MIT"

[lib]
name = "redismodule"
crate-type = ["rlib"] 

[dependencies]
libc = "0.2.18"
bitflags = "0.7"


