[package]
description = "redismodule"
name = "redismodule"
version = "0.1.1"
authors = ["faineance <faineance@users.noreply.github.com>"]
license = "MIT"

[dependencies]
libc = "0.2.18"
bitflags = "0.7"


